# Generated by Django 3.2.21 on 2023-09-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrips', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
